# Site settings
title: Time for a Change
header-img: img/home-bg.png
email: lisa.starzyk@gmail.com
copyright_name: lisastar234
description: > # this means to ignore newlines until "baseurl:"
  Where to begin?
baseurl: "" # the subpath of your site, e.g. /blog
twitter_username: 
github_username:  lisastar234
learn_profile: lisastar234
email_username: lisa.starzyk@gmail.com

# Build settings
markdown: kramdown
highlighter: rouge
permalink: pretty
paginate: 5
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]

gems: [jekyll-paginate, jekyll-feed]
